CREATE TABLE crime_reports (
    dr_no BIGINT PRIMARY KEY,
    date_rptd DATE,
    date_occ DATE,
    time_occ VARCHAR(10),
    area INT,
    area_name VARCHAR(50),
    crm_cd INT,
    crm_cd_desc VARCHAR(255),
    mocodes VARCHAR(255),
    vict_age INT,
    vict_sex CHAR(1),
    vict_descent CHAR(1),
    premis_cd INT,
    premis_desc VARCHAR(255),
    weapon_used_cd VARCHAR(50),
    weapon_desc VARCHAR(255),
    status VARCHAR(10),
    status_desc VARCHAR(255),
    location VARCHAR(255),
    cross_street VARCHAR(255),
    lat NUMERIC(10,6),
    lon NUMERIC(10,6),
    crime_category VARCHAR(50),
    weapon_category VARCHAR(50)
);
